apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: detection
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/max-scale: '3'
    spec:
      containers:
      - image: 29061999/knative-video-detection@sha256:477b697dae923281790d4064a2261b8a704b38baeae904a23a3b24ee0022e87d
        ports:
        - containerPort: 8080
      nodeSelector:
        kubernetes.io/hostname: pi4
