apiVersion: v1
kind: Service
metadata:
  labels:
    app: capture
    service: capture
  name: capture
spec:
  ports:
  - name: tcp-send
    port: 9000
    targetPort: 9000
  selector:
    app: capture
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: capture
    version: v1
  name: capture-v1
spec:
  replicas: 28
  selector:
    matchLabels:
      app: capture
      version: v1
  template:
    metadata:
      labels:
        app: capture
        version: v1
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - "while true; \ndo \n  ./capture 127.0.0.1\ndone\n"
        image: kienkauko/capture2021:0.3
        name: capture
        ports:
        - containerPort: 9000
          name: tcp-send
        volumeMounts:
        - mountPath: /etc/localtime
          name: tz-vietnam
      nodeSelector:
        kubernetes.io/hostname: pi4
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
        name: tz-vietnam
