apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: nginx
spec:
  template:
    metadata:
      # This is the name of our new "Revision," it must follow the convention {service-name}-{revision-name}
      name: nginx-test
      annotations:
        autoscaling.knative.dev/max-scale: "3"
    spec:
      nodeSelector:
        kubernetes.io/hostname: master
      containers:
        - image: nginx@sha256:b495f952df67472c3598b260f4b2e2ba9b5a8b0af837575cf4369c95c8d8a215
          ports:
            - containerPort: 80